/**
 * Danh ngôn v0.2 — 365 câu suy ngẫm đa lĩnh vực, theo đúng thứ tự ngày trong năm.
 *
 * The numbering IS the calendar mapping: line 1 belongs to January 1st, line 365 to
 * December 31st, and the year itself turns the wheel (see `daily-thoughts.ts`). That only
 * works if the list stays exactly 365 lines, in exactly this order — so this file's shape
 * is part of the contract, and the tests hold it there.
 *
 * v0.2 change over v0.1: every "hơn / nhất" comparison is gone. A line states what is true
 * on its own terms; it does not need to rank itself above something else to be honest.
 */

export type MaximSection = {
  /** The grouping a line belongs to. Shown nowhere — it keeps the list balanced. */
  theme: string;
  /** The lines, in day order within the section. */
  lines: readonly string[];
};

export const MAXIM_SECTIONS: readonly MaximSection[] = [
  {
    theme: "Niềm tin",
    lines: [
      "Niềm tin không phải là biết chắc mọi thứ sẽ ổn — mà là dám bước tiếp khi chưa biết.",
      "Có những điều chỉ nhìn rõ được khi ta ngừng cố kiểm soát nó.",
      "Tin vào một điều thiêng liêng cho ta chỗ dựa để lớn lên.",
      "Nghi ngờ không phải là kẻ thù của niềm tin — nó là con đường niềm tin phải đi qua để trưởng thành.",
      "Một hạt giống không thấy được gốc rễ đang mọc trong tối — nhưng nó vẫn lớn.",
      "Có những lời cầu nguyện được trả lời bằng sự im lặng — không phải bằng sự từ chối.",
      "Bình an không đến từ việc hiểu hết mọi chuyện, mà từ việc tin rằng mình không phải hiểu hết mới sống được.",
      "Niềm tin bền vững là niềm tin đã từng bị thử thách và không gãy.",
      "Đừng lẫn lộn giữa im lặng của điều thiêng liêng và sự vắng mặt của nó.",
      "Có một sự khiêm nhường trong việc thừa nhận: không phải mọi câu hỏi đều cần lời đáp ngay hôm nay.",
      "Tin tưởng là quyết định lặp lại mỗi sáng, không phải một lần chọn rồi thôi.",
      "Con đường đức tin không thẳng — nó vòng qua những chỗ ta không ngờ tới.",
      "Một người có niềm tin không phải là người không sợ, mà là người bước tới dù đang sợ.",
      "Ơn phước đôi khi mang hình dạng của một cánh cửa đóng lại đúng lúc.",
      "Ta không cần thấy cả cây cầu — chỉ cần đủ ánh sáng cho bước chân kế tiếp.",
      "Có một sự tự do lớn khi buông bỏ nhu cầu phải kiểm soát mọi kết quả.",
      "Niềm tin không xoá đi nỗi đau — nó cho nỗi đau một chỗ để không trở thành cay đắng.",
      "Ai từng chờ đợi trong im lặng lâu mới hiểu: chờ đợi cũng là một hình thức của lòng tin.",
      "Có những mùa gieo không thấy gặt — nhưng không có nghĩa là hạt giống đã chết.",
      "Tin vào điều tốt lành là một lựa chọn có ý thức, ngay cả giữa một thế giới đầy lý do để nghi ngờ.",
      "Một sự khiêm nhường thật sự là nhận ra mình không phải trung tâm của mọi câu chuyện.",
      "Có một loại can đảm chỉ đến từ việc biết mình không đơn độc trong hành trình.",
      "Đừng đo niềm tin bằng cảm xúc của một ngày — hãy đo bằng lựa chọn của một đời.",
      "Một trái tim biết ơn dễ nhận ra ơn phước, một trái tim đang tìm lý do để phàn nàn thì khó.",
      "Có những câu trả lời chỉ hiện ra khi nhìn lại, không phải khi đang ở giữa cơn bão.",
      "Niềm tin không cần phải to tiếng để chân thật.",
      "Ai gieo trong nước mắt có thể gặt trong vui mừng — nhưng phải qua mùa gieo trước.",
      "Có một sự bình an không phụ thuộc vào hoàn cảnh xung quanh có yên ổn hay không.",
      "Tin cậy là để tay mình mở ra, ngay cả khi không chắc điều gì sẽ được đặt vào đó.",
      "Một đời sống có niềm tin không phải là một đời không vấp ngã — mà là một đời biết đứng dậy vì tin rằng còn đường phía trước.",
      "Cuối ngày, câu hỏi không phải \"mình đã hiểu hết chưa\" mà là \"mình đã tin đủ để bước tiếp chưa\".",
    ],
  },
  {
    theme: "Tuổi trẻ",
    lines: [
      "Tuổi trẻ không phải là một con số — là sự sẵn lòng bắt đầu lại một lần nữa.",
      "Sai lầm ở tuổi trẻ không phải là thất bại — đó là học phí cho sự trưởng thành.",
      "Đừng vội trở thành người lớn tới mức quên mất cách tò mò như một đứa trẻ.",
      "Thanh xuân không phải để tiêu xài — đó là vốn liếng để đầu tư cho phần đời còn lại.",
      "Người trẻ hay hỏi \"tôi muốn gì\" — một câu hỏi đáng suy ngẫm khác là \"tôi sẽ trở thành ai\".",
      "Không ai đánh giá thấp một người trẻ biết lắng nghe.",
      "Sức trẻ không nằm ở tốc độ — nó nằm ở khả năng đứng dậy sau vấp ngã.",
      "Hãy phạm sai lầm khi còn được phép sai — đó là đặc quyền không kéo dài mãi.",
      "Tuổi trẻ dễ nhầm sự bốc đồng với can đảm — hai thứ đó không giống nhau.",
      "Người trẻ khôn ngoan không phải người biết nhiều, mà là người dám thừa nhận mình chưa biết.",
      "Ước mơ không có kế hoạch chỉ là một giấc mơ đẹp; ước mơ có kỷ luật mới thành con đường.",
      "Ai dành tuổi trẻ để xây nền tảng sẽ dùng phần đời còn lại để gặt hái.",
      "Đừng để tiếng ồn của đám đông át đi tiếng nói bên trong mình.",
      "Sự tự tin thật sự không đến từ việc biết mọi câu trả lời, mà từ việc không sợ không biết.",
      "Người trẻ hay muốn đi nhanh — nhưng những gì bền vững thường cần thời gian.",
      "Hãy chọn bạn đồng hành kỹ như chọn con đường mình đi, vì họ sẽ định hình con đường đó.",
      "Kỷ luật ở tuổi trẻ là món quà mà bản thân tương lai sẽ biết ơn.",
      "Không có tuổi trẻ nào lãng phí nếu nó được dùng để học cách yêu thương đúng đắn.",
      "So sánh mình với người khác là một cách đánh mất niềm vui của chính hành trình mình.",
      "Người trẻ dám hỏi \"tại sao\" là người sẽ không sống một cuộc đời sao chép.",
      "Thất bại ở tuổi hai mươi vẫn còn nhiều thời gian để sửa — hãy tận dụng điều đó.",
      "Sự nông nổi không phải là tội — nhưng từ chối học từ nó thì có.",
      "Tuổi trẻ là mùa để gieo những gì bạn muốn gặt ở tuổi trung niên.",
      "Ai dành thời gian nuôi dưỡng một kỹ năng thay vì chạy theo trăm thứ sẽ tiến xa trên con đường mình chọn.",
      "Không ai bắt bạn phải có mọi câu trả lời ở tuổi hai mươi — chỉ cần có phương hướng.",
      "Sự khiêm tốn học được sớm sẽ giúp tránh được nhiều bài học đau đớn về sau.",
      "Một người trẻ đáng quý không hẳn là người tài năng, mà là người kiên trì.",
      "Đầu tư vào chính mình ở tuổi trẻ là khoản đầu tư không bao giờ mất giá.",
      "Tuổi trẻ trôi qua nhanh — hãy sống nó với sự chủ ý, không phải sự trôi dạt.",
      "Một người trẻ biết ơn những gì mình đang có thường tìm thấy hạnh phúc, còn chỉ nhìn vào những gì mình chưa có dễ dẫn tới bất an.",
    ],
  },
  {
    theme: "Tình yêu",
    lines: [
      "Yêu thương không phải là cảm giác luôn nồng nhiệt — đó là quyết định luôn hiện diện.",
      "Tình yêu bền vững được xây bằng những điều nhỏ lặp lại, không phải những khoảnh khắc lớn thỉnh thoảng.",
      "Yêu một người là chọn nhìn thấy điều tốt nhất trong họ, ngay cả những ngày họ không thể tự nhìn thấy nó.",
      "Sự tha thứ là ngôn ngữ tình yêu ít được nói đến nhưng cần thiết.",
      "Một tình yêu chân thật chọn ở lại ngay cả khi có thể chọn rời đi.",
      "Yêu thương thật sự không đòi hỏi đối phương phải hoàn hảo — nó đòi hỏi cả hai cùng cố gắng.",
      "Lắng nghe là một hình thức của tình yêu thường bị đánh giá thấp.",
      "Tình yêu không phải là tìm người hoàn hảo, mà là học cách yêu một người không hoàn hảo một cách trọn vẹn.",
      "Sự quan tâm nhỏ được lặp lại đều đặn xây dựng nên một tình yêu bền vững.",
      "Yêu ai đó là muốn điều tốt cho họ, không chỉ muốn điều tốt cho chính mình từ họ.",
      "Một mối quan hệ lớn lên không phải nhờ không có xung đột, mà nhờ cách xử lý xung đột.",
      "Tình yêu trưởng thành không cố thay đổi người kia — nó tạo không gian để họ tự thay đổi.",
      "Ngôn ngữ yêu thương không giống nhau ở mỗi người — học ngôn ngữ của người mình yêu là một hành động yêu thương.",
      "Sự chân thành có thể khó nghe, nhưng nó xây dựng một nền tảng bền vững.",
      "Yêu thương không có nghĩa là đồng ý với mọi điều — đôi khi nó có nghĩa là nói ra sự thật với lòng tử tế.",
      "Một cái ôm đúng lúc có thể nói lên điều mà lời nói khó diễn tả hết.",
      "Tình yêu cần được nuôi dưỡng như một khu vườn — bỏ mặc, nó sẽ cỗi cằn dù từng xanh tốt.",
      "Yêu người khác bắt đầu từ việc học cách yêu chính mình một cách lành mạnh.",
      "Sự ghen tuông không phải là bằng chứng của tình yêu sâu đậm — nó thường là bằng chứng của sự bất an.",
      "Tình yêu trưởng thành biết khi nào cần nói, và khi nào chỉ cần im lặng bên cạnh.",
      "Không có công thức nào cho tình yêu hoàn hảo — chỉ có sự sẵn lòng học lại mỗi ngày.",
      "Yêu thương là để người kia được là chính họ, không phải phiên bản mình muốn họ trở thành.",
      "Một lời xin lỗi chân thành có sức chữa lành thật sự.",
      "Tình yêu không đo bằng cường độ của một khoảnh khắc, mà bằng độ bền của một cam kết.",
      "Yêu ai đó nghĩa là chọn họ, không chỉ một lần, mà mỗi ngày, kể cả những ngày khó khăn.",
      "Sự tôn trọng là nền móng mà không có nó, tình yêu sẽ không đứng vững lâu.",
      "Đừng chờ đến khi mất đi mới nói lời yêu thương — hãy nói khi còn có thể nghe thấy nó.",
      "Tình yêu trưởng thành không cần chứng minh cho ai khác thấy — nó chỉ cần đúng thật với hai người trong đó.",
      "Một mối quan hệ lành mạnh là nơi cả hai người đều được tốt lên, không phải nơi một người phải nhỏ lại để người kia lớn lên.",
      "Yêu thương đôi khi là buông tay — vì sự trói buộc không phải là tình yêu, đó là sự sở hữu.",
      "Một tình yêu sâu sắc thường không ồn ào — nó lặng lẽ có mặt đúng lúc cần.",
    ],
  },
  {
    theme: "Trưởng thành",
    lines: [
      "Trưởng thành không phải là ngừng cảm thấy tổn thương — mà là học cách xử lý nó mà không làm tổn thương người khác.",
      "Có một ngày ta nhận ra: trưởng thành là làm điều đúng ngay cả khi không ai nhìn thấy.",
      "Người trưởng thành không cần phải đúng trong mọi cuộc tranh luận.",
      "Trưởng thành là học cách chịu trách nhiệm cho cảm xúc của mình, thay vì đổ lỗi cho hoàn cảnh.",
      "Một dấu hiệu của sự trưởng thành là khả năng trì hoãn sự hài lòng tức thời vì một điều tốt đẹp về sau.",
      "Trưởng thành không có nghĩa là hết đau — nó có nghĩa là học cách mang nỗi đau mà không để nó điều khiển mình.",
      "Người trưởng thành biết khi nào cần xin lỗi trước, dù không phải lỗi hoàn toàn của mình.",
      "Sự trưởng thành thật sự thể hiện rõ khi không có ai đang theo dõi.",
      "Học cách nói \"tôi không biết\" là một bước trưởng thành không dễ dàng.",
      "Trưởng thành là ngừng chờ người khác thay đổi để mình được hạnh phúc.",
      "Có một sự tự do lớn khi không còn cần sự công nhận của mọi người để cảm thấy đủ.",
      "Người trưởng thành xử lý xung đột bằng cách nói chuyện, không phải bằng cách im lặng trừng phạt.",
      "Trưởng thành là học cách biết ơn cả những bài học đến từ đau khổ.",
      "Không ai trưởng thành trong vùng an toàn — sự phát triển luôn đòi hỏi một chút khó chịu.",
      "Người trưởng thành biết phân biệt giữa việc quan tâm và việc kiểm soát.",
      "Trưởng thành có nghĩa là chấp nhận rằng không phải ai cũng sẽ hiểu mình, và điều đó cũng ổn thôi.",
      "Sự khiêm tốn không phải là nghĩ mình kém cỏi — đó là nghĩ về mình ít lại.",
      "Người trưởng thành học cách tha thứ cho chính lỗi lầm của quá khứ mình.",
      "Trưởng thành là khi ta bắt đầu chọn điều đúng thay vì điều dễ dàng.",
      "Có một sức mạnh thầm lặng trong việc giữ lời hứa với chính mình.",
      "Người trưởng thành không cần thắng mọi cuộc tranh cãi để cảm thấy mình đúng.",
      "Trưởng thành là học cách sống với những câu hỏi chưa có lời đáp.",
      "Một người trưởng thành biết khi nào cần lùi lại, không phải vì yếu đuối mà vì khôn ngoan.",
      "Trưởng thành không đến theo tuổi tác — nó đến từ những gì ta chọn làm với những gì đã trải qua.",
      "Người trưởng thành hiểu rằng cảm xúc là thật, nhưng không phải lúc nào cũng là sự thật.",
      "Trưởng thành là học cách để người khác được sai mà không cần mình sửa họ ngay lập tức.",
      "Có một sự bình yên khi không còn cần phải chứng minh giá trị của mình cho ai cả.",
      "Người trưởng thành biết ơn quá khứ mà không sống mãi trong đó.",
      "Trưởng thành là chấp nhận rằng một số cánh cửa đóng lại để những cánh cửa khác mở ra.",
      "Một dấu hiệu của trưởng thành có lẽ là sự bình thản khi đối diện với điều không chắc chắn.",
    ],
  },
  {
    theme: "Công việc",
    lines: [
      "Một công việc đáng quý không phải là công việc dễ dàng, mà là công việc giúp ta trưởng thành qua từng ngày.",
      "Sự xuất sắc không phải là một hành động — nó là một thói quen được lặp lại mỗi ngày.",
      "Làm việc chăm chỉ mà không có phương hướng giống như chèo thuyền thật nhanh mà không biết bến đến.",
      "Uy tín được xây trong nhiều năm, nhưng có thể mất trong một quyết định.",
      "Người làm việc giỏi thường là người biết hỏi câu hỏi đúng.",
      "Trách nhiệm không phải là gánh nặng — đó là dấu hiệu cho thấy có người tin tưởng mình.",
      "Một công việc có ý nghĩa không nhất thiết phải lớn lao — nó chỉ cần được làm với sự tận tâm.",
      "Sự chuyên nghiệp thể hiện rõ ở cách một người xử lý sai lầm của chính mình.",
      "Đừng đánh giá công việc chỉ bằng mức lương — hãy đánh giá bằng những gì nó dạy mình.",
      "Người lãnh đạo giỏi không phải là người có mọi câu trả lời, mà là người biết lắng nghe đội của mình.",
      "Kỷ luật trong công việc là cầu nối giữa mục tiêu và thành tựu.",
      "Một ngày làm việc tốt không phải là một ngày không có khó khăn, mà là một ngày ta không bỏ cuộc trước khó khăn.",
      "Sự tin cậy trong công việc được xây từ những cam kết nhỏ được giữ đúng hẹn.",
      "Đừng ngại làm công việc nhỏ một cách xuất sắc — nó thường mở ra cánh cửa cho công việc lớn hơn.",
      "Người thành công bền vững thường là người học được cách thất bại một cách khôn ngoan.",
      "Công việc có giá trị là công việc thật sự tạo ra điều tốt cho ai đó.",
      "Sự khiêm tốn trong công việc là sẵn lòng học từ người ít kinh nghiệm hơn mình.",
      "Một đội nhóm mạnh không phải là đội không có bất đồng, mà là đội biết giải quyết bất đồng một cách tôn trọng.",
      "Năng suất thật sự không phải là làm nhiều việc, mà là làm đúng việc.",
      "Người làm việc có trách nhiệm không cần ai giám sát mới hoàn thành tốt phần việc của mình.",
      "Sự sáng tạo trong công việc thường đến từ những giới hạn, không phải từ sự tự do tuyệt đối.",
      "Đừng để công việc định nghĩa giá trị con người mình — hãy để giá trị con người mình định hình cách làm việc.",
      "Một lời cảm ơn chân thành với đồng nghiệp mang một sức mạnh đáng kể.",
      "Người làm việc giỏi biết khi nào cần nghỉ ngơi để làm việc tốt về sau.",
      "Sự chính trực trong công việc là làm đúng ngay cả khi không ai kiểm tra.",
      "Thành công không đến từ việc không bao giờ sai, mà từ việc sẵn lòng sửa sai nhanh chóng.",
      "Một công việc được làm với lòng biết ơn mang lại niềm vui khác hẳn một công việc làm vì bắt buộc.",
      "Người quản lý giỏi là người giúp người khác thành công, không chỉ lo cho thành công của riêng mình.",
      "Đầu tư vào việc học một kỹ năng mới hôm nay là gieo hạt cho cơ hội của ngày mai.",
      "Sự kiên nhẫn trong công việc thường được đền đáp bằng những kết quả mà sự vội vàng không bao giờ đạt tới.",
      "Cuối cùng, một công việc đáng quý là công việc để lại điều gì đó tốt đẹp khi ta rời khỏi nó.",
    ],
  },
  {
    theme: "Học tập",
    lines: [
      "Học không phải để chứng minh mình biết nhiều, mà để hiểu mình còn phải học bao nhiêu.",
      "Sai lầm là một học phí cho những bài học đắt giá.",
      "Người ham học không sợ bị hỏi những câu mình chưa biết trả lời.",
      "Kiến thức không có sự áp dụng chỉ là thông tin nằm im.",
      "Học một điều mới ở tuổi nào cũng có giá trị — não bộ không có hạn tuổi để phát triển.",
      "Đọc sách là cách để sống nhiều cuộc đời khác nhau.",
      "Người khiêm tốn luôn mở lòng học hỏi, khác với người tự cho mình đã biết đủ.",
      "Thất bại trong học tập không phải là kết thúc — nó là dữ liệu cho lần thử tiếp theo.",
      "Học từ người khác là một cách để tránh bớt những sai lầm không cần thiết.",
      "Sự tò mò là một động cơ bền bỉ trong việc học, không kém gì áp lực bên ngoài.",
      "Một câu hỏi hay tự thân đã mang giá trị lớn.",
      "Học không phải là nhồi nhét thông tin, mà là rèn cách tư duy.",
      "Người giỏi thật sự vẫn tiếp tục học sau khi đã thành công.",
      "Không có kiến thức nào là lãng phí, dù chưa thấy chỗ dùng ngay lúc này.",
      "Học từ thất bại của người khác giúp ta tránh bớt những cái giá phải trả.",
      "Sự kiên trì trong học tập là một nền tảng bền vững, không thể thay thế bằng tài năng bẩm sinh đơn thuần.",
      "Một người thầy giỏi không dạy ta phải nghĩ gì, mà dạy ta cách tự suy nghĩ.",
      "Học cách lắng nghe phản biện là một kỹ năng quý giá, cần được rèn luyện như học cách trình bày ý kiến của mình.",
      "Kiến thức không đi cùng sự khiêm tốn dễ trở thành kiêu ngạo.",
      "Người học suốt đời không bao giờ cảm thấy mình đã \"xong\".",
      "Một sai lầm được phân tích kỹ mang lại giá trị học hỏi, dù không được ai chú ý tới.",
      "Học ngôn ngữ mới không chỉ là học từ vựng — đó là học một cách nhìn thế giới khác.",
      "Sự tập trung sâu trong một giờ có thể tạo ra điều mà một ngày phân tâm không làm được.",
      "Không ai học được thay cho ta — nhưng ai cũng có thể học được từ người khác chỉ đường.",
      "Học cách quản lý thời gian là học cách quản lý chính cuộc đời mình.",
      "Kiến thức thật sự thể hiện ở khả năng giải thích đơn giản một điều phức tạp.",
      "Người học giỏi không hẳn là người nhớ được nhiều, mà là người biết áp dụng đúng lúc.",
      "Một cuốn sổ ghi chú được duy trì đều đặn là một công cụ học tập đáng quý.",
      "Học từ thất bại đòi hỏi lòng dũng cảm nhìn thẳng vào điều mình đã làm sai.",
      "Cuối cùng, mục tiêu của việc học không phải là biết tất cả, mà là biết cách tiếp tục học suốt đời.",
    ],
  },
  {
    theme: "Gia đình",
    lines: [
      "Gia đình không phải là nơi hoàn hảo — đó là nơi ta được yêu thương dù không hoàn hảo.",
      "Một bữa cơm cùng nhau đôi khi mang sức chữa lành mà lời nói khó làm được.",
      "Thời gian dành cho gia đình không bao giờ là thời gian lãng phí, dù không tạo ra kết quả đo đếm được.",
      "Cha mẹ không cần hoàn hảo — họ chỉ cần hiện diện và chân thành.",
      "Một cuộc gọi hỏi thăm ngắn ngủi có thể là điều người thân đang chờ cả ngày.",
      "Gia đình là nơi ta được là chính mình mà không cần diễn.",
      "Sự tha thứ trong gia đình không dễ dàng, nhưng luôn cần thiết, vì ta còn phải sống cùng nhau lâu dài.",
      "Không có thành công nào ngoài kia bù đắp được cho một gia đình bị bỏ quên.",
      "Lắng nghe con cái nói, ngay cả những điều nhỏ nhặt, xây dựng niềm tin lớn về sau.",
      "Gia đình mạnh mẽ không phải vì không có mâu thuẫn, mà vì biết cách quay lại với nhau sau mâu thuẫn.",
      "Một lời \"cảm ơn\" hay \"xin lỗi\" trong nhà thường bị tiết kiệm một cách đáng tiếc.",
      "Di sản lớn nhất cha mẹ để lại không phải là tài sản, mà là cách họ đã sống.",
      "Gia đình là đội đầu tiên ta thuộc về.",
      "Đôi khi yêu thương gia đình là biết khi nào cần im lặng lắng nghe, khi nào cần khuyên bảo.",
      "Một mái nhà ấm áp không cần rộng lớn — nó chỉ cần đầy ắp sự quan tâm.",
      "Truyền thống gia đình nhỏ bé, lặp lại mỗi năm, tạo nên ký ức lớn cho con cái sau này.",
      "Chăm sóc cha mẹ già là cách trả lại tình yêu đã nhận từ khi còn bé.",
      "Gia đình không đòi hỏi ta phải thành công — họ chỉ cần ta bình an trở về.",
      "Một người anh chị biết lắng nghe có thể là một chỗ dựa quý giá.",
      "Nuôi dạy con không phải là uốn nắn chúng theo ý mình, mà là giúp chúng trở thành chính mình.",
      "Gia đình là nơi những thất bại bên ngoài được đón nhận mà không bị phán xét.",
      "Một cái nắm tay đúng lúc trong gia đình đôi khi nói lên điều mà ngàn lời động viên không diễn tả hết.",
      "Ký ức đẹp trong gia đình thường không phải những chuyến đi xa hoa, mà là những khoảnh khắc bình thường được chia sẻ cùng nhau.",
      "Sự hiện diện chân thành là điều cha mẹ có thể mang lại, không cần phải hoàn hảo.",
      "Gia đình dạy ta bài học đầu tiên về tình yêu vô điều kiện.",
      "Đôi khi điều một người thân cần nhất không phải là lời khuyên, mà là một người ngồi cạnh.",
      "Một gia đình biết ơn nhau thường tìm thấy hạnh phúc trong những điều bình thường mỗi ngày.",
      "Nuôi dưỡng mối quan hệ với anh chị em cần sự chủ động, không tự nhiên mà bền vững.",
      "Gia đình là nơi ta học cách yêu thương người không hoàn hảo — bài học áp dụng cho cả cuộc đời.",
      "Một câu chuyện được kể lại qua nhiều thế hệ giữ cho gốc rễ gia đình không bị lãng quên.",
      "Cuối cùng, thứ quý giá gia đình cho ta không phải là những gì họ có, mà là cảm giác thuộc về.",
    ],
  },
  {
    theme: "Kiên trì & Nghịch cảnh",
    lines: [
      "Kiên trì không phải là không bao giờ muốn bỏ cuộc — đó là tiếp tục dù rất muốn bỏ cuộc.",
      "Nghịch cảnh không định nghĩa con người ta — cách ta phản ứng với nó mới định nghĩa.",
      "Có những bài học chỉ có thể học được qua đau khổ, không có đường tắt nào khác.",
      "Người kiên trì không nhất thiết có sức mạnh đặc biệt — họ chỉ từ chối dừng lại.",
      "Cơn bão nào cũng qua — câu hỏi là ta sẽ là ai khi nó qua đi.",
      "Thất bại chỉ là vĩnh viễn khi ta ngừng thử lại.",
      "Sức mạnh thật sự không phải là không bao giờ ngã, mà là luôn sẵn lòng đứng dậy sau mỗi lần ngã.",
      "Có một loại trưởng thành chỉ đến từ việc sống sót qua điều tưởng như không thể vượt qua.",
      "Nghịch cảnh là người thầy khắc nghiệt nhưng dạy những bài học sâu sắc.",
      "Đừng so sánh chương khó khăn của mình với chương dễ dàng của người khác — mỗi người có một câu chuyện riêng.",
      "Kiên trì trong im lặng vẫn mang một sức mạnh riêng, dù không được ai tán dương.",
      "Một người từng vượt qua khó khăn lớn thường trở nên dịu dàng với khó khăn của người khác.",
      "Không phải mọi vết thương đều để lại sẹo xấu — một số trở thành nguồn sức mạnh.",
      "Sự bền bỉ nhỏ mỗi ngày cộng dồn thành sức mạnh lớn theo thời gian.",
      "Khi không thể thay đổi hoàn cảnh, ta vẫn có thể chọn cách mình đối diện với nó.",
      "Nghịch cảnh bóc trần con người thật — cả điểm yếu lẫn sức mạnh chưa từng biết mình có.",
      "Có những cánh cửa chỉ mở ra sau khi một cánh cửa khác đã đóng lại đau đớn.",
      "Kiên nhẫn với chính mình trong khó khăn quan trọng không kém kiên nhẫn với hoàn cảnh.",
      "Người từng ngã nhiều lần thường mang theo một sự vững vàng mà chỉ trải nghiệm mới dạy được.",
      "Không phải mọi cuộc chiến đều cần thắng ngay — một số chỉ cần không bỏ cuộc.",
      "Sự chịu đựng có giới hạn, nhưng sức mạnh của tinh thần con người là điều đáng kinh ngạc.",
      "Nghịch cảnh dạy ta phân biệt ai thật sự ở lại và ai chỉ ở lại khi mọi thứ dễ dàng.",
      "Một ngày tồi tệ không có nghĩa là một cuộc đời tồi tệ.",
      "Kiên trì không cần phải ồn ào — đôi khi nó chỉ là thức dậy và thử lại một lần nữa.",
      "Đau khổ không được chọn, nhưng ý nghĩa rút ra từ nó là điều ta có thể chọn.",
      "Một người mạnh mẽ không phải là người không bao giờ khóc, mà là người khóc xong vẫn đứng dậy.",
      "Có một sự bình an đến sau cơn bão mà chỉ ai đã trải qua cơn bão mới hiểu được.",
      "Nghịch cảnh không phải để phá hủy ta — nó thường là nơi ta khám phá ra sức mạnh của chính mình.",
      "Đừng đánh giá thấp sức mạnh của việc chỉ đơn giản là không từ bỏ.",
      "Cuối cùng, một câu chuyện đáng nhớ không phải là câu chuyện không có khó khăn, mà là câu chuyện đã vượt qua nó.",
    ],
  },
  {
    theme: "Lòng biết ơn",
    lines: [
      "Biết ơn không phải là phớt lờ điều chưa tốt — đó là chọn nhìn thấy điều đã tốt song song với nó.",
      "Một trái tim biết ơn tìm thấy đủ đầy trong những điều nhỏ.",
      "Biết ơn quá khứ không có nghĩa là phải thích mọi điều đã xảy ra — chỉ là nhận ra nó đã hình thành nên mình hôm nay.",
      "Người biết ơn hiếm khi cảm thấy thiếu thốn.",
      "Một lời cảm ơn chân thành có thể thay đổi cả ngày của một người khác.",
      "Biết ơn là liều thuốc giải cho sự so sánh — chúng không thể tồn tại cùng lúc.",
      "Đếm những điều mình có thường mang lại bình an, còn đếm những điều mình thiếu thường mang lại lo âu.",
      "Lòng biết ơn biến những gì ta có thành đủ.",
      "Một ngày bắt đầu bằng lòng biết ơn thường kết thúc nhẹ nhàng.",
      "Biết ơn những người thầy khó tính đôi khi đến muộn — nhưng khi đến, nó thường sâu sắc.",
      "Sự hài lòng không đến từ việc có nhiều, mà từ việc biết ơn những gì đang có.",
      "Người biết ơn thường hào phóng, vì họ không sợ mất đi những gì mình đã nhận được dồi dào.",
      "Biết ơn cả những mùa khó khăn, vì chúng thường dạy những bài học mà mùa thuận lợi không dạy được.",
      "Một cái nhìn biết ơn có thể tìm thấy ánh sáng ngay cả trong ngày u ám.",
      "Đừng chờ đến khi mất đi mới học cách biết ơn những gì đang có.",
      "Lòng biết ơn không phụ thuộc vào hoàn cảnh bên ngoài — nó là một lựa chọn từ bên trong.",
      "Người biết ơn sức khỏe của mình thường chăm sóc nó chu đáo, không coi đó là điều hiển nhiên.",
      "Một cuốn sổ ghi lại ba điều biết ơn mỗi tối có thể thay đổi cách một người nhìn cả cuộc đời mình.",
      "Biết ơn những người đã rời đi cũng quan trọng như biết ơn những người đang ở lại.",
      "Sự biết ơn nuôi dưỡng niềm vui; sự đòi hỏi nuôi dưỡng bất mãn.",
      "Một người biết ơn công việc của mình, dù nhỏ, thường làm nó một cách tận tâm.",
      "Biết ơn không đòi hỏi hoàn cảnh phải hoàn hảo — nó chỉ đòi hỏi một đôi mắt biết nhìn.",
      "Có những điều bình thường mỗi ngày — một mái nhà, một bữa ăn, một người thân — xứng đáng được biết ơn một cách trọn vẹn.",
      "Lòng biết ơn với chính cơ thể mình là bước đầu để đối xử tử tế với nó.",
      "Một người biết ơn quá khứ khó khăn của mình thường có lòng trắc ẩn sâu sắc với người khác.",
      "Biết ơn không làm mờ đi vấn đề thật — nó cho ta sức mạnh để đối diện với vấn đề đó.",
      "Sự biết ơn với những người thầm lặng giúp đỡ ta thường bị bỏ quên.",
      "Một khoảnh khắc dừng lại để biết ơn có thể làm chậm cả một ngày vội vã lại.",
      "Biết ơn là một cách đơn giản để tăng thêm hạnh phúc mỗi ngày.",
      "Người biết ơn thời gian mình có thường dùng nó có chủ đích.",
      "Cuối cùng, biết ơn không thay đổi hoàn cảnh — nó thay đổi cách ta sống trong hoàn cảnh đó.",
    ],
  },
  {
    theme: "Tha thứ & Bình an nội tâm",
    lines: [
      "Tha thứ không phải là nói điều sai đã đúng — đó là buông gánh nặng để tự do bước tiếp.",
      "Giữ oán giận giống như uống thuốc độc rồi chờ người khác chết.",
      "Bình an nội tâm không đến từ việc mọi thứ xung quanh đều ổn, mà từ việc ta không còn cần mọi thứ phải ổn.",
      "Tha thứ cho chính mình là một phần quan trọng của hành trình chữa lành.",
      "Một trái tim mang oán giận lâu ngày tự mình trở nên nặng nề.",
      "Bình an không phải là không có bão tố — đó là sự tĩnh lặng ở giữa cơn bão.",
      "Tha thứ không có nghĩa là quên — nó có nghĩa là không để quá khứ điều khiển hiện tại.",
      "Sự tĩnh lặng của tâm trí là một điều quý giá, dễ bị lãng quên giữa sự ồn ào của thành công.",
      "Tha thứ là món quà ta cho chính mình, không chỉ cho người được tha thứ.",
      "Một người bình an không cần phải đúng trong mọi việc để cảm thấy ổn.",
      "Buông bỏ điều không thể thay đổi là bước đầu tiên để tìm lại bình an.",
      "Tha thứ không đòi hỏi phải tin tưởng lại ngay lập tức — nó chỉ đòi hỏi buông bỏ sự cay đắng.",
      "Bình an nội tâm là biết phân biệt điều gì đáng để lo lắng và điều gì không.",
      "Một tâm hồn bình an có thể ở giữa hỗn loạn mà không bị cuốn theo nó.",
      "Tha thứ cho lỗi lầm của bản thân là điều kiện để bắt đầu lại một cách trọn vẹn.",
      "Sự im lặng có chủ đích đôi khi mang sức chữa lành mà một cuộc tranh cãi kéo dài không thể mang lại.",
      "Bình an không phải là đích đến — nó là cách ta chọn đi trên con đường mỗi ngày.",
      "Tha thứ giải phóng ta khỏi vai trò nạn nhân của quá khứ.",
      "Một người học cách sống chậm lại thường tìm thấy bình an mà người vội vã bỏ lỡ.",
      "Ôm giữ tổn thương không trừng phạt người đã gây ra nó — nó chỉ kéo dài nỗi đau của chính ta.",
      "Bình an đến khi ta ngừng chiến đấu với những điều đã thuộc về quá khứ.",
      "Tha thứ không phải là yếu đuối — đó là một hành động can đảm.",
      "Một tâm trí yên tĩnh có thể nghe thấy những điều một tâm trí ồn ào bỏ lỡ.",
      "Bình an nội tâm được xây dựng từ những ranh giới lành mạnh, không phải từ việc làm hài lòng tất cả mọi người.",
      "Tha thứ mở ra không gian cho những mối quan hệ mới, thay vì bị chiếm chỗ bởi những vết thương cũ.",
      "Có một sự nhẹ nhõm lớn khi buông bỏ nhu cầu phải thắng trong mọi cuộc tranh cãi.",
      "Bình an không có nghĩa là không còn cảm xúc mạnh — nó có nghĩa là không bị cảm xúc đó cuốn đi.",
      "Tha thứ là một quá trình, không phải một quyết định một lần là xong.",
      "Một người tìm được bình an với quá khứ của mình thường sống trọn vẹn ở hiện tại.",
      "Cuối cùng, bình an nội tâm không phải là phần thưởng cho một cuộc đời hoàn hảo — nó là món quà cho một trái tim đã học cách buông bỏ.",
    ],
  },
  {
    theme: "Sức khỏe & Cân bằng sống",
    lines: [
      "Sức khỏe không phải là thứ ta có, mà là thứ ta chăm sóc mỗi ngày.",
      "Nghỉ ngơi không phải là lười biếng — đó là một phần của công việc, không phải sự phản bội nó.",
      "Một cơ thể được lắng nghe sẽ ít khi phải lên tiếng bằng bệnh tật.",
      "Cân bằng không có nghĩa là chia đều thời gian cho mọi thứ — nó có nghĩa là ưu tiên đúng điều quan trọng lúc này.",
      "Giấc ngủ đủ giấc là một khoản đầu tư đơn giản cho sức khỏe lâu dài.",
      "Chăm sóc cơ thể là cách thể hiện lòng biết ơn với món quà duy nhất ta có suốt đời.",
      "Sự vội vã liên tục là kẻ thù thầm lặng của sức khỏe tinh thần.",
      "Một bước đi bộ ngắn ngoài trời đôi khi chữa lành tâm trí theo cách mà suy nghĩ một mình không làm được.",
      "Cân bằng cuộc sống không phải là một trạng thái tĩnh — nó là một điều chỉnh liên tục.",
      "Sức khỏe tinh thần cũng cần được chăm sóc nghiêm túc như sức khỏe thể chất.",
      "Một hơi thở sâu có chủ đích có thể làm dịu cả một cơn giận đang bùng lên.",
      "Nói \"không\" với một việc đôi khi là nói \"có\" với sức khỏe của chính mình.",
      "Cơ thể ghi nhớ những gì tâm trí cố quên — chăm sóc cả hai cùng lúc.",
      "Sự cân bằng thật sự là biết khi nào cần cố gắng và khi nào cần nghỉ ngơi.",
      "Ăn uống điều độ là một hành động yêu thương bản thân âm thầm mỗi ngày.",
      "Một tâm trí quá tải cũng cần được nghỉ ngơi như một cơ thể mệt mỏi.",
      "Sức khỏe không chỉ là không có bệnh — đó là có đủ năng lượng để sống trọn vẹn.",
      "Đừng đợi đến khi kiệt sức mới nghĩ đến việc nghỉ ngơi.",
      "Một khoảng lặng nhỏ giữa ngày bận rộn mang một giá trị đáng kể.",
      "Chăm sóc bản thân không phải là ích kỷ — đó là điều kiện để có thể chăm sóc người khác.",
      "Sự cân bằng giữa công việc và nghỉ ngơi là kỷ luật, không phải sự may mắn.",
      "Một giấc ngủ ngon thường mang lại một góc nhìn mới cho những vấn đề của ngày hôm qua.",
      "Sức khỏe lâu dài được xây từ những thói quen nhỏ lặp lại, không phải từ những nỗ lực bùng nổ thỉnh thoảng.",
      "Cơ thể là nơi ta sống suốt đời — đáng để chăm sóc nó cẩn thận.",
      "Một chút vận động đều đặn mỗi ngày xây dựng sức khỏe bền vững.",
      "Cân bằng đôi khi có nghĩa là chấp nhận một ngày không hoàn hảo mà không tự trách mình.",
      "Sức khỏe tinh thần được nuôi dưỡng bởi những mối quan hệ lành mạnh xung quanh mình.",
      "Nghỉ ngơi đúng lúc là một cách để duy trì hiệu quả làm việc lâu dài.",
      "Một cơ thể được chăm sóc tốt là nền tảng cho những ước mơ khác có thể thực hiện được.",
      "Sự tĩnh lặng có chủ đích mỗi ngày là món quà cho sức khỏe tinh thần lâu dài.",
      "Cuối cùng, chăm sóc bản thân hôm nay là món quà gửi cho phiên bản của mình mười năm sau.",
    ],
  },
  {
    theme: "Ước mơ, Mục đích & Trách nhiệm",
    lines: [
      "Một ước mơ không có hành động chỉ là một suy nghĩ dễ chịu.",
      "Mục đích sống không phải lúc nào cũng lớn lao — đôi khi nó chỉ đơn giản là làm tốt điều trước mắt.",
      "Trách nhiệm là cái giá của sự tự do — càng tự do, càng cần gánh vác nhiều.",
      "Ước mơ lớn cần được chia thành những bước nhỏ mới có thể đi được.",
      "Người sống có mục đích không cần đợi hoàn cảnh hoàn hảo mới bắt đầu.",
      "Trách nhiệm với người khác bắt đầu từ trách nhiệm với chính lời nói và hành động của mình.",
      "Một cuộc đời có ý nghĩa không đo bằng những gì đạt được, mà bằng những gì đã cho đi.",
      "Ước mơ mà không có kỷ luật đi kèm thường chỉ dừng lại ở tưởng tượng.",
      "Sống có trách nhiệm là làm điều đúng, kể cả khi điều đó không dễ dàng hay không được ai công nhận.",
      "Mục đích sống rõ ràng biến những khó khăn hằng ngày thành những bước đi có ý nghĩa.",
      "Đừng đợi đến khi có đủ mọi điều kiện mới bắt đầu theo đuổi điều mình tin tưởng.",
      "Trách nhiệm không phải là gánh nặng bị áp đặt — đó là dấu hiệu của một cuộc đời trưởng thành.",
      "Một người có mục đích rõ ràng ít khi bị lung lay bởi ý kiến của đám đông.",
      "Ước mơ cần được nuôi dưỡng bằng hành động mỗi ngày, không chỉ bằng cảm xúc mỗi khi nghĩ tới nó.",
      "Sống có trách nhiệm với thời gian của mình là tôn trọng chính cuộc đời mình đang có.",
      "Mục đích không cần phải thay đổi thế giới — thay đổi một góc nhỏ xung quanh mình cũng đủ ý nghĩa.",
      "Người theo đuổi ước mơ nghiêm túc chấp nhận cả những ngày không có tiến triển rõ ràng.",
      "Trách nhiệm với gia đình, công việc, và chính mình cần được cân bằng, không cái nào nên hoàn toàn lấn át cái khác.",
      "Một ước mơ đáng theo đuổi thường đòi hỏi sự hy sinh mà không phải ai cũng sẵn lòng trả.",
      "Sống có mục đích là biết mình đang đi đâu, ngay cả khi con đường chưa rõ ràng từng bước.",
      "Một trách nhiệm quan trọng của một người có lẽ là sống đúng với những giá trị mình tin tưởng.",
      "Ước mơ không thành hiện thực không có nghĩa là nó vô nghĩa — hành trình theo đuổi nó đã thay đổi con người mình.",
      "Một cuộc đời có trách nhiệm là một cuộc đời người khác có thể tin cậy được.",
      "Mục đích sống thường được khám phá dần dần qua hành động, không phải qua suy nghĩ một mình.",
      "Trách nhiệm với cộng đồng bắt đầu từ những việc nhỏ: giữ lời hứa, tôn trọng người khác, sống trung thực.",
      "Ước mơ càng lớn càng cần một nền tảng vững chắc của kỷ luật và kiên trì.",
      "Sống có mục đích nghĩa là mỗi ngày trôi qua đều mang lại điều gì đó có ý nghĩa, dù nhỏ.",
      "Trách nhiệm và tình yêu thường đi cùng nhau — yêu thương thật sự luôn kéo theo trách nhiệm.",
      "Cuối năm nhìn lại, câu hỏi quan trọng không phải là \"mình đã đạt được gì\", mà là \"mình đã trở thành ai, và mình đã sống có trách nhiệm, có yêu thương, có trọn vẹn hay chưa\".",
    ],
  },
] as const;
