-- AVORA-89 · PHẦN 2 · 2.4b — Mẫu bảng library: "để làm gì" × "dành cho ai"; + think_hub_open_questions (kệ 2).
set search_path = '';

alter table public.think_hub_template add column if not exists audiences text[] not null default '{moi_nguoi}';
alter table public.think_hub_template add column if not exists when_to_use text;
alter table public.think_hub_template add column if not exists example_rows jsonb;
alter table public.think_hub_template drop constraint if exists think_hub_template_audiences_check;
alter table public.think_hub_template add constraint think_hub_template_audiences_check check (
  cardinality(audiences) >= 1 and audiences <@ array['moi_nguoi','hoc_sinh','gia_dinh','doanh_nhan','sales','ke_toan','ky_thuat']::text[]);
alter table public.think_hub_template drop constraint if exists think_hub_template_example_rows_check;
alter table public.think_hub_template add constraint think_hub_template_example_rows_check check (
  example_rows is null or (jsonb_typeof(example_rows) = 'array' and jsonb_array_length(example_rows) <= 2));

-- existing templates: only the three new columns (no column / key change, boards made from them untouched)
update public.think_hub_template set audiences = array['moi_nguoi']::text[], when_to_use = 'Phải chọn giữa vài phương án.' where key = 'weigh_options';
update public.think_hub_template set audiences = array['moi_nguoi']::text[], when_to_use = 'Một chuyện cứ lặp lại, chưa rõ gốc.' where key = 'problem';
update public.think_hub_template set audiences = array['moi_nguoi','doanh_nhan']::text[], when_to_use = 'Sắp làm việc lớn, muốn lường trước.' where key = 'count_cost';
update public.think_hub_template set audiences = array['moi_nguoi','hoc_sinh']::text[], when_to_use = 'Đầu năm / đầu kỳ.' where key = 'year_goals';
update public.think_hub_template set audiences = array['moi_nguoi','gia_dinh']::text[], when_to_use = 'Tổ chức tiệc, lễ, chuyến đi.' where key = 'event';
update public.think_hub_template set audiences = array['gia_dinh']::text[], when_to_use = 'Việc chung của cả nhà.' where key = 'family_plan';
update public.think_hub_template set audiences = array['gia_dinh']::text[], when_to_use = 'Gom những thứ cần mua.' where key = 'shopping';
update public.think_hub_template set audiences = array['doanh_nhan','ky_thuat']::text[], when_to_use = 'Một dự án nhiều phần, nhiều người.' where key = 'project_plan';
update public.think_hub_template set audiences = array['doanh_nhan','ke_toan','ky_thuat']::text[], when_to_use = 'Làm việc với nhiều nhà cung cấp.' where key = 'suppliers';
update public.think_hub_template set audiences = array['sales','doanh_nhan']::text[], when_to_use = 'Theo đuổi nhiều khách cùng lúc.' where key = 'customers';
update public.think_hub_template set audiences = array['ky_thuat']::text[], when_to_use = 'Theo dõi một công trình từ đầu tới bàn giao.' where key = 'construction';

-- 21 new templates
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('lessons', 'Bài học rút ra', 'learn', 'Lần sau mình sẽ làm khác điều gì?', 'Cột: Chuyện gì · Học được gì · Lần sau làm gì · Ngày', array['journal','direct','group','project']::text[], '[{"type": "text", "label": "Học được gì"}, {"type": "text", "label": "Lần sau làm gì"}, {"type": "date", "label": "Ngày"}]'::jsonb, '[{"key": "moi", "label": "Mới ghi"}, {"key": "da_ap_dung", "label": "Đã áp dụng", "done": true}]'::jsonb, 'Chuyện gì', 'table', array['Học được gì']::text[], 1, true, 200, array['moi_nguoi']::text[], 'Vừa xong một việc, muốn lần sau làm tốt hơn.', '[{"title": "Họp khách trễ 20 phút", "Học được gì": "Không xếp 2 cuộc sát nhau", "Lần sau làm gì": "Chừa 30 phút giữa hai cuộc"}, {"title": "Báo giá thiếu phí vận chuyển", "Học được gì": "Luôn hỏi địa điểm giao", "Lần sau làm gì": "Thêm dòng vận chuyển vào mẫu báo giá"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('exam_plan', 'Kế hoạch ôn thi', 'breakdown', 'Phần nào mình chưa chắc?', 'Cột: Phần · Môn · Ngày ôn · Mức chắc', array['journal','direct','group']::text[], '[{"type": "text", "label": "Môn"}, {"type": "date", "label": "Ngày ôn"}, {"type": "select", "label": "Mức chắc", "options": ["Chưa chắc", "Tạm được", "Chắc rồi"]}]'::jsonb, '[{"key": "chua_on", "label": "Chưa ôn"}, {"key": "dang_on", "label": "Đang ôn"}, {"key": "da_on", "label": "Đã ôn", "done": true}]'::jsonb, 'Phần', 'table', array['Môn']::text[], 1, true, 210, array['hoc_sinh']::text[], 'Trước kỳ thi.', '[{"title": "Hàm số bậc hai", "Môn": "Toán", "Mức chắc": "Chưa chắc"}, {"title": "Thì hiện tại hoàn thành", "Môn": "Tiếng Anh", "Mức chắc": "Tạm được"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('homework', 'Bài tập & hạn nộp', 'track', 'Bài nào cần làm trước?', 'Cột: Bài · Môn · Hạn · Đã nộp', array['journal','direct','group']::text[], '[{"type": "text", "label": "Môn"}, {"type": "date", "label": "Hạn"}, {"type": "select", "label": "Đã nộp", "options": ["Chưa", "Đã nộp"]}]'::jsonb, '[{"key": "chua_lam", "label": "Chưa làm"}, {"key": "dang_lam", "label": "Đang làm"}, {"key": "da_nop", "label": "Đã nộp", "done": true}]'::jsonb, 'Bài', 'table', array['Môn']::text[], 1, true, 220, array['hoc_sinh']::text[], 'Nhiều môn, nhiều hạn.', '[{"title": "Bài luận 500 chữ", "Môn": "Văn", "Đã nộp": "Chưa"}, {"title": "Phiếu bài tập chương 3", "Môn": "Lý", "Đã nộp": "Đã nộp"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('subject_notes', 'Ghi chú một môn học', 'learn', 'Điều này áp dụng vào đâu?', 'Cột: Khái niệm · Ví dụ · Câu hỏi còn mở · Nguồn', array['journal','direct','group']::text[], '[{"type": "text", "label": "Ví dụ"}, {"type": "text", "label": "Câu hỏi còn mở"}, {"type": "text", "label": "Nguồn"}]'::jsonb, '[{"key": "dang_hoc", "label": "Đang học"}, {"key": "da_hieu", "label": "Đã hiểu", "done": true}]'::jsonb, 'Khái niệm', 'table', array['Ví dụ']::text[], 1, true, 230, array['hoc_sinh']::text[], 'Học khái niệm mới.', '[{"title": "Lực ma sát", "Ví dụ": "Phanh xe đạp", "Câu hỏi còn mở": "Vì sao đường ướt trơn hơn?"}, {"title": "Cung và cầu", "Ví dụ": "Giá rau tăng sau bão", "Nguồn": "SGK Kinh tế 10"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('choose_school', 'Chọn trường · chọn ngành', 'weigh', 'Mình hợp với điều gì nhất?', 'Cột: Trường / ngành · Điểm chuẩn · Hợp sở thích · Chi phí · Khoảng cách', array['journal','direct','group']::text[], '[{"type": "number", "label": "Điểm chuẩn"}, {"type": "select", "label": "Hợp sở thích", "options": ["Rất hợp", "Tạm", "Không"]}, {"type": "number", "label": "Chi phí"}, {"type": "text", "label": "Khoảng cách"}]'::jsonb, '[{"key": "dang_can_nhac", "label": "Đang cân nhắc"}, {"key": "chon", "label": "Chọn", "done": true}, {"key": "loai", "label": "Loại", "done": true}]'::jsonb, 'Trường / ngành', 'table', array['Điểm chuẩn']::text[], 1, true, 240, array['hoc_sinh']::text[], 'Chọn nguyện vọng.', '[{"title": "Bách khoa · Cơ khí", "Điểm chuẩn": "25", "Hợp sở thích": "Rất hợp"}, {"title": "Kinh tế · Marketing", "Điểm chuẩn": "26", "Hợp sở thích": "Tạm"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('learn_skill', 'Học một kỹ năng', 'progress', 'Bước tiếp theo nhỏ nhất là gì?', 'Cột: Bước · Tài liệu · Ngày xong', array['journal','direct','group']::text[], '[{"type": "text", "label": "Tài liệu"}, {"type": "date", "label": "Ngày xong"}]'::jsonb, '[{"key": "chua_bat_dau", "label": "Chưa bắt đầu"}, {"key": "dang_hoc", "label": "Đang học"}, {"key": "xong", "label": "Xong", "done": true}]'::jsonb, 'Bước', 'table', array['Tài liệu']::text[], 1, true, 250, array['hoc_sinh','moi_nguoi']::text[], 'Tự học ngoại ngữ, nhạc cụ…', '[{"title": "Học 5 hợp âm cơ bản", "Tài liệu": "Video kênh guitar"}, {"title": "Đánh trọn bài đầu tiên"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('weekly_menu', 'Thực đơn tuần', 'progress', 'Tuần này nhà mình ăn gì cho đủ chất?', 'Cột: Món · Ngày · Bữa · Cần mua', array['journal','direct','group']::text[], '[{"type": "text", "label": "Ngày"}, {"type": "select", "label": "Bữa", "options": ["Sáng", "Trưa", "Tối"]}, {"type": "text", "label": "Cần mua"}]'::jsonb, '[{"key": "du_kien", "label": "Dự kiến"}, {"key": "da_nau", "label": "Đã nấu", "done": true}]'::jsonb, 'Món', 'table', array['Ngày']::text[], 1, true, 260, array['gia_dinh']::text[], 'Lên bữa cho cả tuần.', '[{"title": "Canh chua cá lóc", "Ngày": "Thứ Hai", "Bữa": "Tối", "Cần mua": "Cá, me, rau"}, {"title": "Cháo yến mạch", "Ngày": "Thứ Ba", "Bữa": "Sáng"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('family_budget', 'Ngân sách gia đình tháng', 'track', 'Khoản nào đang vượt?', 'Cột: Khoản · Dự kiến · Đã chi · Còn lại', array['journal','direct','group']::text[], '[{"type": "number", "label": "Dự kiến"}, {"type": "number", "label": "Đã chi"}, {"type": "number", "label": "Còn lại"}]'::jsonb, '[{"key": "trong_muc", "label": "Trong mức"}, {"key": "vuot", "label": "Vượt"}, {"key": "xong_thang", "label": "Xong tháng", "done": true}]'::jsonb, 'Khoản', 'table', array['Dự kiến']::text[], 1, true, 270, array['gia_dinh']::text[], 'Chia tiền tháng cho các khoản.', '[{"title": "Đi chợ", "Dự kiến": "6000000", "Đã chi": "4200000", "Còn lại": "1800000"}, {"title": "Học phí", "Dự kiến": "3000000", "Đã chi": "3000000", "Còn lại": "0"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('home_repair', 'Sửa nhà · việc nhà lớn', 'breakdown', 'Việc nào làm trước, việc nào chờ được?', 'Cột: Hạng mục · Ưu tiên · Chi phí ước · Ai làm', array['journal','direct','group']::text[], '[{"type": "select", "label": "Ưu tiên", "options": ["Gấp", "Sớm", "Chờ được"]}, {"type": "number", "label": "Chi phí ước"}, {"type": "text", "label": "Ai làm"}]'::jsonb, '[{"key": "chua_lam", "label": "Chưa làm"}, {"key": "dang_lam", "label": "Đang làm"}, {"key": "xong", "label": "Xong", "done": true}]'::jsonb, 'Hạng mục', 'table', array['Ưu tiên']::text[], 1, true, 280, array['gia_dinh']::text[], 'Sửa chữa, sắm sửa lớn.', '[{"title": "Chống thấm mái", "Ưu tiên": "Gấp", "Chi phí ước": "8000000"}, {"title": "Sơn lại phòng khách", "Ưu tiên": "Chờ được"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('kids_school', 'Việc học của con', 'track', 'Con đang cần mình giúp ở đâu?', 'Cột: Việc · Con · Môn / lớp · Lịch · Ghi chú', array['journal','direct','group']::text[], '[{"type": "text", "label": "Con"}, {"type": "text", "label": "Môn / lớp"}, {"type": "text", "label": "Lịch"}, {"type": "text", "label": "Ghi chú"}]'::jsonb, '[{"key": "dang_theo", "label": "Đang theo"}, {"key": "xong", "label": "Xong", "done": true}]'::jsonb, 'Việc', 'table', array['Con']::text[], 1, true, 290, array['gia_dinh']::text[], 'Nhiều lịch học, nhiều môn của con.', '[{"title": "Học bơi", "Con": "Bin", "Lịch": "T3, T5 · 17h"}, {"title": "Ôn Toán cuối kỳ", "Con": "Na", "Môn / lớp": "Toán 5"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('biz_idea', 'Ý tưởng kinh doanh', 'weigh', 'Ai cần điều này, và họ trả tiền thế nào?', 'Cột: Ý tưởng · Ai cần · Kiếm tiền · Rủi ro · Thử nhỏ thế nào', array['journal','direct','group','project']::text[], '[{"type": "text", "label": "Ai cần"}, {"type": "text", "label": "Kiếm tiền"}, {"type": "text", "label": "Rủi ro"}, {"type": "text", "label": "Thử nhỏ thế nào"}]'::jsonb, '[{"key": "dang_nghi", "label": "Đang nghĩ"}, {"key": "thu", "label": "Thử", "done": true}, {"key": "bo", "label": "Bỏ", "done": true}]'::jsonb, 'Ý tưởng', 'table', array['Ai cần']::text[], 1, true, 300, array['doanh_nhan']::text[], 'Có ý mới, muốn biết có đáng thử.', '[{"title": "Giao cơm văn phòng", "Ai cần": "Nhân viên khu công nghiệp", "Thử nhỏ thế nào": "20 suất / ngày trong 2 tuần"}, {"title": "Cho thuê dụng cụ cắm trại", "Rủi ro": "Hư hỏng, mất đồ"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('risks', 'Rủi ro cần để mắt', 'track', 'Nếu chuyện này xảy ra, mình làm gì?', 'Cột: Rủi ro · Khả năng · Ảnh hưởng · Cách giảm · Người theo', array['journal','direct','group','project']::text[], '[{"type": "select", "label": "Khả năng", "options": ["Thấp", "Vừa", "Cao"]}, {"type": "select", "label": "Ảnh hưởng", "options": ["Nhỏ", "Vừa", "Lớn"]}, {"type": "text", "label": "Cách giảm"}, {"type": "text", "label": "Người theo"}]'::jsonb, '[{"key": "dang_theo", "label": "Đang theo"}, {"key": "da_giam", "label": "Đã giảm", "done": true}]'::jsonb, 'Rủi ro', 'table', array['Khả năng']::text[], 1, true, 310, array['doanh_nhan']::text[], 'Nhiều rủi ro cùng lúc.', '[{"title": "Nhà cung cấp chính tăng giá", "Khả năng": "Vừa", "Ảnh hưởng": "Lớn", "Cách giảm": "Tìm thêm 1 nguồn"}, {"title": "Nhân sự chủ chốt nghỉ", "Khả năng": "Thấp", "Ảnh hưởng": "Lớn"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('hiring', 'Tuyển người', 'progress', 'Người này có hợp việc và hợp đội không?', 'Cột: Ứng viên · Vị trí · Nhận xét', array['journal','group','project']::text[], '[{"type": "text", "label": "Vị trí"}, {"type": "text", "label": "Nhận xét"}]'::jsonb, '[{"key": "ho_so", "label": "Hồ sơ"}, {"key": "phong_van", "label": "Phỏng vấn"}, {"key": "nhan", "label": "Nhận", "done": true}, {"key": "khong", "label": "Không phù hợp", "done": true}]'::jsonb, 'Ứng viên', 'table', array['Vị trí']::text[], 1, true, 320, array['doanh_nhan']::text[], 'Đang tuyển một vị trí.', '[{"title": "Ứng viên A", "Vị trí": "Kế toán", "Nhận xét": "Kinh nghiệm 3 năm"}, {"title": "Ứng viên B", "Vị trí": "Kế toán"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('quarter_goals', 'Mục tiêu quý', 'breakdown', 'Kết quả nào chứng tỏ mình đã tới?', 'Cột: Mục tiêu · Kết quả đo được · Người phụ trách · Mức đạt', array['journal','group','project']::text[], '[{"type": "text", "label": "Kết quả đo được"}, {"type": "text", "label": "Người phụ trách"}, {"type": "select", "label": "Mức đạt", "options": ["0%", "25%", "50%", "75%", "100%"]}]'::jsonb, '[{"key": "dang_lam", "label": "Đang làm"}, {"key": "dat", "label": "Đạt", "done": true}, {"key": "chua_dat", "label": "Chưa đạt", "done": true}]'::jsonb, 'Mục tiêu', 'table', array['Kết quả đo được']::text[], 1, true, 330, array['doanh_nhan']::text[], 'Đầu quý.', '[{"title": "Tăng khách quay lại", "Kết quả đo được": "30% khách mua lần 2", "Mức đạt": "25%"}, {"title": "Rút ngắn giao hàng", "Kết quả đo được": "≤ 2 ngày"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('objections', 'Xử lý lời từ chối', 'learn', 'Khách thật sự lo điều gì?', 'Cột: Khách nói · Lo thật · Cách đáp · Hiệu quả', array['journal','direct','group']::text[], '[{"type": "text", "label": "Lo thật"}, {"type": "text", "label": "Cách đáp"}, {"type": "select", "label": "Hiệu quả", "options": ["Chưa thử", "Được", "Rất tốt"]}]'::jsonb, '[{"key": "dang_thu", "label": "Đang thử"}, {"key": "dung_tot", "label": "Dùng tốt", "done": true}]'::jsonb, 'Khách nói', 'table', array['Lo thật']::text[], 1, true, 340, array['sales']::text[], 'Gom câu khách hay nói và cách đáp tốt.', '[{"title": "“Giá cao quá”", "Lo thật": "Sợ không đáng tiền", "Cách đáp": "So chi phí 3 năm, không chỉ giá mua", "Hiệu quả": "Được"}, {"title": "“Để anh suy nghĩ thêm”", "Lo thật": "Chưa đủ tin", "Cách đáp": "Mời xem công trình đã làm"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('weekly_visits', 'Kế hoạch gặp khách tuần', 'progress', 'Gặp ai trước thì có lợi nhất?', 'Cột: Khách · Mục đích gặp · Ngày · Kết quả', array['journal','direct','group']::text[], '[{"type": "text", "label": "Mục đích gặp"}, {"type": "date", "label": "Ngày"}, {"type": "text", "label": "Kết quả"}]'::jsonb, '[{"key": "du_kien", "label": "Dự kiến"}, {"key": "da_gap", "label": "Đã gặp", "done": true}, {"key": "hoan", "label": "Hoãn", "done": true}]'::jsonb, 'Khách', 'table', array['Mục đích gặp']::text[], 1, true, 350, array['sales']::text[], 'Lên lịch gặp khách trong tuần.', '[{"title": "Công ty Minh Phát", "Mục đích gặp": "Gửi báo giá đợt 2"}, {"title": "Anh Quí · kho Bình Dương", "Mục đích gặp": "Khảo sát mặt bằng"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('competitors', 'Đối thủ & điểm khác biệt', 'weigh', 'Vì sao khách nên chọn mình?', 'Cột: Đối thủ · Mạnh · Yếu · Mình khác ở đâu', array['journal','direct','group','project']::text[], '[{"type": "text", "label": "Mạnh"}, {"type": "text", "label": "Yếu"}, {"type": "text", "label": "Mình khác ở đâu"}]'::jsonb, '[{"key": "dang_tim", "label": "Đang tìm hiểu"}, {"key": "ro", "label": "Đã rõ", "done": true}]'::jsonb, 'Đối thủ', 'table', array['Mạnh']::text[], 1, true, 360, array['sales','doanh_nhan']::text[], 'Chuẩn bị chào hàng.', '[{"title": "Đối thủ A", "Mạnh": "Giá thấp", "Yếu": "Bảo hành ngắn", "Mình khác ở đâu": "Bảo hành 3 năm, có kỹ thuật tại chỗ"}, {"title": "Đối thủ B", "Mạnh": "Thương hiệu lớn"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('tax_calendar', 'Lịch nộp thuế & báo cáo', 'track', 'Kỳ nào sắp tới hạn?', 'Cột: Loại · Kỳ · Hạn · Người làm', array['journal','group','project']::text[], '[{"type": "text", "label": "Kỳ"}, {"type": "date", "label": "Hạn"}, {"type": "text", "label": "Người làm"}]'::jsonb, '[{"key": "chua_lam", "label": "Chưa làm"}, {"key": "dang_lam", "label": "Đang làm"}, {"key": "da_nop", "label": "Đã nộp", "done": true}]'::jsonb, 'Loại', 'table', array['Kỳ']::text[], 1, true, 370, array['ke_toan','doanh_nhan']::text[], 'Nhiều kỳ, nhiều loại báo cáo.', '[{"title": "Tờ khai GTGT", "Kỳ": "Quý 3"}, {"title": "Quyết toán TNCN", "Kỳ": "Năm 2025"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('reconcile', 'Đối chiếu công nợ', 'track', 'Chênh ở đâu, vì sao?', 'Cột: Đối tác · Số theo sổ · Số đối tác · Chênh · Ghi chú', array['journal','group','project']::text[], '[{"type": "number", "label": "Số theo sổ"}, {"type": "number", "label": "Số đối tác"}, {"type": "number", "label": "Chênh"}, {"type": "text", "label": "Ghi chú"}]'::jsonb, '[{"key": "chua_khop", "label": "Chưa khớp"}, {"key": "da_khop", "label": "Đã khớp", "done": true}]'::jsonb, 'Đối tác', 'table', array['Số theo sổ']::text[], 1, true, 380, array['ke_toan']::text[], 'Cuối tháng / cuối quý.', '[{"title": "Công ty Minh Phát", "Số theo sổ": "120000000", "Số đối tác": "118500000", "Chênh": "1500000", "Ghi chú": "Thiếu 1 hoá đơn vận chuyển"}, {"title": "Nhà cung cấp B", "Chênh": "0"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('missing_docs', 'Chứng từ còn thiếu', 'track', 'Còn thiếu gì, ai giữ?', 'Cột: Chứng từ · Nghiệp vụ · Ai giữ · Hạn bổ sung', array['journal','group','project']::text[], '[{"type": "text", "label": "Nghiệp vụ"}, {"type": "text", "label": "Ai giữ"}, {"type": "date", "label": "Hạn bổ sung"}]'::jsonb, '[{"key": "thieu", "label": "Còn thiếu"}, {"key": "da_du", "label": "Đã đủ", "done": true}]'::jsonb, 'Chứng từ', 'table', array['Nghiệp vụ']::text[], 1, true, 390, array['ke_toan']::text[], 'Gom chứng từ chưa đủ.', '[{"title": "Hoá đơn tiếp khách 12/09", "Nghiệp vụ": "Chi phí bán hàng", "Ai giữ": "Chị Lan"}, {"title": "Biên bản giao hàng lô 7", "Ai giữ": "Kho"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;
insert into public.think_hub_template (key, name, thinking_type, guiding_question, description, scopes, column_defs, status_options, title_label, default_view, mobile_columns, version, is_active, sort_order, audiences, when_to_use, example_rows)
values ('handover_check', 'Kiểm tra trước khi giao', 'track', 'Điều gì có thể làm khách không hài lòng?', 'Cột: Hạng mục · Tiêu chí · Đạt / chưa · Ảnh · Người kiểm', array['journal','group','project']::text[], '[{"type": "text", "label": "Tiêu chí"}, {"type": "select", "label": "Đạt / chưa", "options": ["Chưa kiểm", "Đạt", "Chưa đạt"]}, {"type": "text", "label": "Ảnh"}, {"type": "text", "label": "Người kiểm"}]'::jsonb, '[{"key": "chua_kiem", "label": "Chưa kiểm"}, {"key": "dat", "label": "Đạt", "done": true}, {"key": "sua_lai", "label": "Sửa lại"}]'::jsonb, 'Hạng mục', 'table', array['Tiêu chí']::text[], 1, true, 400, array['ky_thuat']::text[], 'Trước bàn giao công trình / sản phẩm.', '[{"title": "Đèn hành lang tầng 2", "Tiêu chí": "Sáng đều, không nhấp nháy", "Đạt / chưa": "Đạt"}, {"title": "Ổ cắm phòng họp", "Tiêu chí": "Đủ 6 ổ, chạy thử tải", "Đạt / chưa": "Chưa kiểm"}]'::jsonb)
on conflict (key) do update set name = excluded.name, thinking_type = excluded.thinking_type, guiding_question = excluded.guiding_question, description = excluded.description, scopes = excluded.scopes, column_defs = excluded.column_defs, status_options = excluded.status_options, title_label = excluded.title_label, mobile_columns = excluded.mobile_columns, sort_order = excluded.sort_order, audiences = excluded.audiences, when_to_use = excluded.when_to_use, example_rows = excluded.example_rows;

-- ---------------------------------------------------------------- kệ 2 · what is still unsettled (read only, no copy)
-- Per board of mine: empty cells in non-system columns, whether a conclusion exists, when someone else last changed it.
create or replace function public.think_hub_open_questions()
returns table (table_id uuid, empty_cells integer, has_conclusion boolean, others_changed_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
declare v_user uuid := auth.uid();
begin
  perform private.assert_session_allowed();
  if v_user is null then raise exception 'avora_not_signed_in'; end if;
  return query
  select t.id,
    coalesce((select sum((select count(*) from jsonb_array_elements(t.column_defs) c
                          where coalesce(c ->> 'system', 'false') <> 'true' and c ? 'id'
                            and coalesce(r.extension_fields ->> (c ->> 'id'), '') = ''))::integer
              from public.think_hub_record r where r.table_id = t.id and r.deleted_at is null), 0),
    exists (select 1 from public.think_hub_conclusions k where k.table_id = t.id),
    (select max(l.created_at) from public.think_hub_change_log l where l.table_id = t.id and l.actor_id <> v_user)
  from public.think_hub_table t
  where t.deleted_at is null and t.archived_at is null and private.think_hub_table_visible(t.id, v_user);
end $$;
revoke all on function public.think_hub_open_questions() from public, anon;
grant execute on function public.think_hub_open_questions() to authenticated;
